import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { useLocation, useNavigate } from "react-router-dom";
import { IconCheck, IconChevron } from "./icons";
import { useAuth } from "../state/AuthContext";

type Step={title:string;body:string;selector?:string;route?:string};
const STEPS:Step[]=[
{title:"Bienvenue dans Oligens Detector",body:"Bienvenue ! Cette courte visite vous montre où trouver les fonctions principales et comment commencer.",selector:"[data-tour=sidebar]"},
{title:"Tableau de bord",body:"Votre espace d’accueil : retrouvez votre activité, vos résultats et commencez rapidement une nouvelle analyse.",selector:"[data-tour=dashboard]",route:"/dashboard"},
{title:"Analyses",body:"Retrouvez vos documents analysés, leurs résultats et vos rapports.",selector:"[data-tour=analyses]",route:"/analyses"},
{title:"Nouveau scan",body:"Importez un document ou collez votre texte, puis lancez l’analyse. Votre formule détermine le nombre d’analyses disponibles.",selector:"[data-tour=new-scan]",route:"/scan/new"},
{title:"Base institutionnelle",body:"Consultez et organisez les documents et sources de votre espace institutionnel.",selector:"[data-tour=database]",route:"/base-institutionnelle"},
{title:"Rapports",body:"Consultez vos rapports et téléchargez les documents disponibles avec votre formule.",selector:"[data-tour=reports]",route:"/reports"},
{title:"Paramètres",body:"Modifiez vos préférences. Vos changements sont automatiquement enregistrés.",selector:"[data-tour=settings]",route:"/settings"},
{title:"Abonnements",body:"Comparez Flash / Découverte, Oligens Pro et Oligens Gold, leurs limites et leurs fonctionnalités.",selector:"[data-tour=subscriptions]",route:"/subscriptions"},
{title:"Vous êtes prêt",body:"Vous êtes prêt ! Commencez par une nouvelle analyse. Vous pourrez revoir cette visite depuis votre menu Profil."}
];
function storageKey(id:string){return `oligens:onboarding:v1:${id}`}
export default function OnboardingTour(){const{user}=useAuth();const location=useLocation();const navigate=useNavigate();const[open,setOpen]=useState(false);const[index,setIndex]=useState(0);const[rect,setRect]=useState<DOMRect|null>(null);const[target,setTarget]=useState<HTMLElement|null>(null);const step=STEPS[index];
useEffect(()=>{if(!user)return;try{if(localStorage.getItem(storageKey(user.id))!=="done"){const t=window.setTimeout(()=>setOpen(true),700);return()=>window.clearTimeout(t)}}catch{setOpen(true)}},[user]);
useEffect(()=>{if(!open)return;const refresh=()=>{const node=step.selector?document.querySelector<HTMLElement>(step.selector):null;setTarget(node);setRect(node?.getBoundingClientRect()??null)};refresh();window.addEventListener("resize",refresh);window.addEventListener("scroll",refresh,true);return()=>{window.removeEventListener("resize",refresh);window.removeEventListener("scroll",refresh,true)}},[open,index,step.selector,location.pathname]);
const finish=()=>{if(user)try{localStorage.setItem(storageKey(user.id),"done")}catch{}setOpen(false)};
const next=()=>{if(index>=STEPS.length-1)return finish();const n=index+1;setIndex(n);if(STEPS[n].route&&location.pathname!==STEPS[n].route)navigate(STEPS[n].route!)};
useEffect(()=>{const restart=()=>{setIndex(0);setOpen(true)};window.addEventListener("oligens:restart-onboarding",restart);return()=>window.removeEventListener("oligens:restart-onboarding",restart)},[]);
const style=useMemo(()=>{if(!rect)return{top:"50%",left:"50%",transform:"translate(-50%,-50%)"} as const;const width=Math.min(380,window.innerWidth-32);const left=Math.max(16,Math.min(rect.left,window.innerWidth-width-16));const top=rect.bottom+244<window.innerHeight?rect.bottom+14:Math.max(16,rect.top-244);return{top,left,width} as const},[rect]);if(!open||!user)return null;return createPortal(<div className="fixed inset-0 z-[100]"><div className="absolute inset-0 bg-night-950/65 backdrop-blur-[1px]"/>{target&&rect&&<div className="pointer-events-none absolute rounded-xl border-2 border-gold-300 shadow-[0_0_0_9999px_rgba(2,4,10,.58),0_0_30px_rgba(232,189,85,.45)]" style={{left:rect.left-5,top:rect.top-5,width:rect.width+10,height:rect.height+10}}/>}<section className="glass absolute rounded-2xl border border-gold-400/30 p-5 shadow-2xl" style={style} role="dialog" aria-modal="true"><div className="flex items-start justify-between gap-4"><div><p className="label-caps text-gold-400">Visite guidée · {index+1}/{STEPS.length}</p><h2 className="mt-1 font-display text-lg font-bold text-ink-100">{step.title}</h2></div><button type="button" onClick={finish} className="text-xs text-ink-500 hover:text-ink-100">Ignorer</button></div><p className="mt-3 text-[12.5px] leading-relaxed text-ink-300">{step.body}</p><div className="mt-5 flex items-center justify-between gap-3"><div className="flex gap-1.5">{STEPS.map((_,i)=><span key={i} className={`h-1.5 w-5 rounded-full ${i===index?"bg-gold-400":"bg-white/10"}`}/>)}</div><button type="button" onClick={next} className="btn-gold inline-flex items-center gap-2 px-4 py-2 text-[12px]">{index===STEPS.length-1?<><IconCheck className="h-3.5 w-3.5"/>Terminer</>:<>Suivant<IconChevron className="h-3.5 w-3.5 -rotate-90"/></>}</button></div></section></div>,document.body)}
