import { createContext,useCallback,useContext,useEffect,useRef,useState,type ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { fmtInt,type GlobalResults,type RecentEntry,type ReportItem } from "../data";
import { analyzeText } from "../lib/detector/analysisRunner";
import type { FullAnalysisResult } from "../lib/detector/heuristicEngine";
import type { HumanizerReport } from "../lib/humanizer/humanizerUltimate";
import { prefersReducedMotion } from "../ui";
import { useAuth } from "./AuthContext";
export type ScanPhase="idle"|"running"|"done";
export interface AnalysisPayload{name:string;text:string;sizeKo:number;}
export interface LastScan{name:string;text:string;at:number;result:GlobalResults;entry:RecentEntry;analysisId?:string;}
interface Toast{id:number;title:string;body:string;}
interface AnalysisContextValue{phase:ScanPhase;progress:number;activeName:string|null;activeWords:number|null;startScan:(payload:AnalysisPayload,opts?:{redirectTo?:string})=>void;resetScan:()=>void;results:GlobalResults|null;entries:RecentEntry[];lastScan:LastScan|null;analysesCount:number;reports:ReportItem[];reportsCount:number;addReportFromEntry:(entry:RecentEntry)=>ReportItem;humanizerReport:HumanizerReport|null;saveHumanizerReport:(r:HumanizerReport)=>void;reportEntry:RecentEntry|null;openReport:(entry:RecentEntry)=>void;closeReport:()=>void;toasts:Toast[];toast:(title:string,body:string)=>void;dismissToast:(id:number)=>void;refreshData:()=>Promise<void>;}
const AnalysisContext=createContext<AnalysisContextValue|null>(null);
export function mapAnalysis(a:FullAnalysisResult,name:string):GlobalResults{const ia=Math.round(a.probabilite_IA*100),plagiat=a.plagiat_estime;const refs=a.references.total===0?0:Math.min(12,Math.max(2,Math.round(a.references.douteuses/a.references.total*100)));const human=Math.max(0,100-Math.min(100,ia+plagiat+refs));const passages=Math.max(ia>=35?2:0,Math.round(plagiat/3));const top=a.rapport_detaille[0];const ciWidth=(a.intervalle_confiance_95[1]-a.intervalle_confiance_95[0])*100;return{fileName:name,ia,plagiat,refs,human,refsTotal:a.references.total,refsDouteuses:a.references.douteuses,passages,summary:`${fmtInt(a.statistiques.mots)} mots, ${fmtInt(a.statistiques.phrases)} phrases et ${fmtInt(a.statistiques.caracteres)} caractères analysés en ${fmtInt(a.processing.durationMs)} ms (${a.processing.mode==="worker"?"Web Worker dédié":"exécution directe"}). ${top?`Facteur dominant : ${top.nom} (z = ${top.z_score>=0?"+":"−"}${Math.abs(top.z_score).toFixed(2)}). `:""}${a.references.total>0?`${a.references.douteuses} référence${a.references.douteuses>1?"s":""} sur ${a.references.total} n'${a.references.douteuses>1?"ont":"a"} pas pu être vérifiée${a.references.douteuses>1?"s":""}.`:"Aucune référence bibliographique détectée dans le document."}`,origins:a.signature.modeles,confidence:a.confiance_analyse,confidenceInterval:[Math.round(a.intervalle_confiance_95[0]*100),Math.round(a.intervalle_confiance_95[1]*100)],decision:a.decision_precaution,engine:a.processing,language:a.langue,signatureNote:a.signature.note,topFactors:a.rapport_detaille,metrics:{precision:Math.round(ciWidth/2*10)/10,transitionDensity:Math.round(a.features.tauxTransitionStandard*10000)/10,burstiness:Math.round(a.features.burstiness*100)/100,mattr:Math.round(a.features.mattr*100)/100,originalite:a.features.scoreOriginalite,charEntropy:Math.round(a.features.perplexiteRelative*100)/100}};}
function rowToEntry(row:any):RecentEntry{const date=new Date(row.created_at);const kind=(row.file_type==="pdf"||row.file_type==="docx")?row.file_type:"txt";return{id:String(row.id),name:String(row.file_name),kind,date:date.toLocaleDateString("fr-FR",{day:"2-digit",month:"short",year:"numeric"}),time:date.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}),pages:Math.max(1,Math.ceil(Number(row.word_count??0)/300)),ai:Number(row.ai_score??0),plagiat:Number(row.plagiarism_score??0),sizeKo:row.file_size_kb==null?undefined:Number(row.file_size_kb),mots:Number(row.word_count??0)};}
function rowToResult(row:any):GlobalResults|null{if(!row?.analysis_result)return null;try{return typeof row.analysis_result==="string"?JSON.parse(row.analysis_result):row.analysis_result as GlobalResults;}catch{return null;}}
export function AnalysisProvider({children}:{children:ReactNode}){const navigate=useNavigate();const{user}=useAuth();const[phase,setPhase]=useState<ScanPhase>("idle"),[progress,setProgress]=useState(0),[activeName,setActiveName]=useState<string|null>(null),[activeWords,setActiveWords]=useState<number|null>(null),[results,setResults]=useState<GlobalResults|null>(null),[entries,setEntries]=useState<RecentEntry[]>([]),[lastScan,setLastScan]=useState<LastScan|null>(null),[analysesCount,setAnalysesCount]=useState(0),[reports,setReports]=useState<ReportItem[]>([]),[humanizerReport,setHumanizerReport]=useState<HumanizerReport|null>(null),[reportEntry,setReportEntry]=useState<RecentEntry|null>(null),[toasts,setToasts]=useState<Toast[]>([]);const toastId=useRef(0),phaseRef=useRef(phase),pendingRef=useRef<{res:GlobalResults;payload:AnalysisPayload}|null>(null),redirectRef=useRef<string|null>(null);useEffect(()=>{phaseRef.current=phase},[phase]);const toast=useCallback((title:string,body:string)=>{const id=++toastId.current;setToasts(t=>[...t,{id,title,body}]);window.setTimeout(()=>setToasts(t=>t.filter(x=>x.id!==id)),5200)},[]);const dismissToast=useCallback((id:number)=>setToasts(t=>t.filter(x=>x.id!==id)),[]);
 const refreshData=useCallback(async()=>{if(!user){setEntries([]);setReports([]);setResults(null);setLastScan(null);setAnalysesCount(0);return;}try{const [aRes,rRes,sRes]=await Promise.all([fetch("/api/analyses?limit=100",{credentials:"include"}),fetch("/api/reports",{credentials:"include"}),fetch("/api/stats",{credentials:"include"})]);const [aData,rData,sData]=await Promise.all([aRes.json(),rRes.json(),sRes.json()]);if(!aRes.ok)throw new Error(aData.error??"Impossible de charger les analyses.");if(!rRes.ok)throw new Error(rData.error??"Impossible de charger les rapports.");if(!sRes.ok)throw new Error(sData.error??"Impossible de charger les statistiques.");const rows=Array.isArray(aData.analyses)?aData.analyses:[];setEntries(rows.map(rowToEntry));setAnalysesCount(Number(sData.analysesCount??rows.length));setReports((Array.isArray(rData.reports)?rData.reports:[]).map((r:any)=>({id:String(r.id),analysisId:r.analysis_id??undefined,entry:rowToEntry({id:r.analysis_id??r.id,file_name:r.file_name??"Rapport",file_type:r.file_type??"txt",word_count:r.word_count??0,ai_score:r.ai_score??0,plagiarism_score:r.plagiarism_score??0,created_at:r.analysis_created_at??r.created_at}),hash:String(r.report_data?.hash??""),createdAt:new Date(r.created_at).toLocaleString("fr-FR")})));const latest=rows[0];if(latest){const latestResult=rowToResult(latest);if(latestResult){setResults(latestResult);setLastScan({name:String(latest.file_name),text:"",at:new Date(latest.created_at).getTime(),result:latestResult,entry:rowToEntry(latest),analysisId:String(latest.id)});}}}catch(error){toast("Données indisponibles",error instanceof Error?error.message:"Impossible de charger les données.");}},[user,toast]);useEffect(()=>{void refreshData()},[refreshData]);
 const startScan=useCallback((payload:AnalysisPayload,opts?:{redirectTo?:string})=>{if(phaseRef.current==="running"){toast("Analyse en cours","Veuillez patienter avant de lancer une nouvelle analyse.");return;}if(!user){toast("Connexion requise","Connectez-vous pour lancer une analyse.");return;}const wordCount=payload.text.trim()?payload.text.trim().split(/\s+/).length:0;redirectRef.current=opts?.redirectTo??null;setActiveName(payload.name);setActiveWords(wordCount);setProgress(3);setPhase("running");void fetch("/api/usage/consume",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({words:wordCount})}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message??d.error??"Analyse non autorisée.");return analyzeText(payload.text,{language:"auto"})}).then(async analysis=>{const mapped=mapAnalysis(analysis,payload.name);const save=await fetch("/api/analyses/create",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileName:payload.name,sizeKo:payload.sizeKo,result:mapped})});const saved=await save.json().catch(()=>({}));if(!save.ok)throw new Error(saved.error??"Impossible d'enregistrer l'analyse.");pendingRef.current={res:mapped,payload};setProgress(100)}).catch(err=>{setPhase("idle");setProgress(0);setActiveName(null);setActiveWords(null);toast("Analyse bloquée",err instanceof Error?err.message:"Échec de l'analyse.")});},[toast,user]);
 useEffect(()=>{if(phase!=="running")return;const reduced=prefersReducedMotion();const id=window.setInterval(()=>setProgress(p=>p<90?Math.min(90,p+(reduced?30:1.3)+Math.random()*(reduced?30:2.1)):p),reduced?80:110);return()=>window.clearInterval(id)},[phase]);
 useEffect(()=>{if(phase!=="running"||progress<100)return;const pending=pendingRef.current;if(!pending)return;pendingRef.current=null;const{res,payload}=pending,now=new Date(),lower=payload.name.toLowerCase();const entry:RecentEntry={id:`pending-${Date.now()}`,name:payload.name,kind:lower.endsWith(".pdf")?"pdf":lower.endsWith(".docx")||lower.endsWith(".doc")?"docx":"txt",date:now.toLocaleDateString("fr-FR",{day:"2-digit",month:"short",year:"numeric"}),time:now.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}),pages:Math.max(1,Math.round((res.engine?.words??300)/300)),ai:res.ia,plagiat:res.plagiat,fresh:true,sizeKo:payload.sizeKo,mots:res.engine?.words};const t=window.setTimeout(()=>{setResults(res);setEntries(prev=>[entry,...prev].slice(0,100));setLastScan({name:payload.name,text:payload.text,at:Date.now(),result:res,entry});setAnalysesCount(c=>c+1);setPhase("done");toast("Analyse terminée",`${payload.name} — risque IA ${res.ia} % · ${fmtInt(res.engine?.words??0)} mots.`);void refreshData();const redirect=redirectRef.current;if(redirect)window.setTimeout(()=>navigate(redirect),prefersReducedMotion()?200:1600);window.setTimeout(()=>{setPhase("idle");setProgress(0);setActiveName(null);setActiveWords(null)},2400)},420);return()=>window.clearTimeout(t)},[progress,phase,toast,navigate,refreshData]);
 const resetScan=useCallback(()=>{setPhase("idle");setProgress(0);setActiveName(null);setActiveWords(null)},[]);const addReportFromEntry=useCallback((entry:RecentEntry)=>{const id=`pending-${Date.now()}`;void(async()=>{try{if(entry.id.startsWith("pending-")){toast("Rapport indisponible","Cette analyse n'est pas encore persistée dans Neon.");return;}const result=await fetch("/api/reports",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({analysisId:entry.id,reportType:"pdf",reportData:results??{}})});const data=await result.json().catch(()=>({}));if(!result.ok)throw new Error(data.error??"Impossible de créer le rapport.");await refreshData();toast("Rapport enregistré","Le rapport est maintenant conservé dans votre compte.");}catch(error){toast("Rapport non enregistré",error instanceof Error?error.message:"Erreur serveur.")}})();return{id,entry,hash:"",createdAt:new Date().toLocaleString("fr-FR"),analysisId:entry.id}},[results,refreshData,toast]);const saveHumanizerReport=useCallback((r:HumanizerReport)=>setHumanizerReport(r),[]),openReport=useCallback((entry:RecentEntry)=>setReportEntry(entry),[]),closeReport=useCallback(()=>setReportEntry(null),[]);return <AnalysisContext.Provider value={{phase,progress,activeName,activeWords,startScan,resetScan,results,entries,lastScan,analysesCount,reports,reportsCount:reports.length,addReportFromEntry,humanizerReport,saveHumanizerReport,reportEntry,openReport,closeReport,toasts,toast,dismissToast,refreshData}}>{children}</AnalysisContext.Provider>}
export function useAnalysis(){const ctx=useContext(AnalysisContext);if(!ctx)throw new Error("useAnalysis doit être utilisé dans <AnalysisProvider>.");return ctx;}
