import { createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode } from "react";
import type { PlanId } from "../lib/billing/plans";
export interface SubscriptionState{plan:PlanId;status:"active"|"expired"|"cancelled"|"pending";period:"monthly"|"yearly"|"lifetime"|null;currentPeriodEnd:string|null;flashStartedAt:string|null;flashAnalysesToday:number}
export interface AuthUser{id:string;email:string;email_verified:boolean}
const FREE:SubscriptionState={plan:"free",status:"active",period:"monthly",currentPeriodEnd:null,flashStartedAt:null,flashAnalysesToday:0};
interface AuthContextValue{user:AuthUser|null;loading:boolean;subscription:SubscriptionState;signUp:(email:string,password:string)=>Promise<{needsVerification:boolean}>;verifyEmail:(email:string,code:string)=>Promise<void>;signIn:(email:string,password:string)=>Promise<void>;signOut:()=>Promise<void>;refreshSubscription:()=>Promise<void>}
const AuthContext=createContext<AuthContextValue|null>(null);
async function api<T>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,{credentials:"include",headers:{"Content-Type":"application/json",...(options?.headers??{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error??"Une erreur serveur est survenue.");return data as T}
export function AuthProvider({children}:{children:ReactNode}){const[user,setUser]=useState<AuthUser|null>(null);const[loading,setLoading]=useState(true);const[subscription,setSubscription]=useState(FREE);const refreshSubscription=useCallback(async()=>{try{const d=await api<{user:AuthUser|null;subscription:SubscriptionState}>("/api/auth/me");setUser(d.user);setSubscription(d.subscription??FREE)}catch{setUser(null);setSubscription(FREE)}},[]);useEffect(()=>{void refreshSubscription().finally(()=>setLoading(false))},[refreshSubscription]);const signUp=useCallback(async(email:string,password:string)=>api<{needsVerification:boolean}>("/api/auth/signup",{method:"POST",body:JSON.stringify({email,password})}),[]);const verifyEmail=useCallback(async(email:string,code:string)=>{await api("/api/auth/verify",{method:"POST",body:JSON.stringify({email,code})});await refreshSubscription()},[refreshSubscription]);const signIn=useCallback(async(email:string,password:string)=>{await api("/api/auth/signin",{method:"POST",body:JSON.stringify({email,password})});await refreshSubscription()},[refreshSubscription]);const signOut=useCallback(async()=>{await api("/api/auth/signout",{method:"POST"});setUser(null);setSubscription(FREE)},[]);return <AuthContext.Provider value={useMemo(()=>({user,loading,subscription,signUp,verifyEmail,signIn,signOut,refreshSubscription}),[user,loading,subscription,signUp,verifyEmail,signIn,signOut,refreshSubscription])}>{children}</AuthContext.Provider>}
export function useAuth(){const ctx=useContext(AuthContext);if(!ctx)throw new Error("useAuth doit être utilisé dans <AuthProvider>.");return ctx}
