import type { VercelRequest,VercelResponse } from "@vercel/node";
import { getUser } from "../_lib/auth.js";
import { transaction } from "../_lib/db.js";
type Plan="flash"|"pro"|"gold";
type BillingPeriod="month"|"year"|"lifetime";
type DbPeriod="monthly"|"yearly"|"lifetime";
type Provider="zakapro"|"moncash"|"natcash";
const periodMap:Record<BillingPeriod,DbPeriod>={month:"monthly",year:"yearly",lifetime:"lifetime"};
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=="POST")return res.status(405).json({error:"Méthode non autorisée"});try{const user=await getUser(req);if(!user)return res.status(401).json({error:"Connexion requise."});const plan=String(req.body?.plan) as Plan;const billingPeriod=String(req.body?.billingPeriod) as BillingPeriod;const provider=String(req.body?.provider) as Provider;const phone=String(req.body?.phone??"").trim();const promoCode=String(req.body?.promoCode??"").trim().toUpperCase();if(!["flash","pro","gold"].includes(plan)||!periodMap[billingPeriod]||!["zakapro","moncash","natcash"].includes(provider))return res.status(400).json({error:"Paramètres de paiement invalides."});if(!/^\+?509\d{8}$/.test(phone.replace(/[\s-]/g,"")))return res.status(400).json({error:"Numéro haïtien invalide."});const tx=await transaction(async client=>{const price=await client.query<{price_htg:string}>(`SELECT price_htg FROM plan_prices WHERE plan=$1 AND billing_period=$2 AND is_active=true LIMIT 1`,[plan,periodMap[billingPeriod]]);if(!price.rows[0])throw Object.assign(new Error("Le tarif sélectionné n'est pas configuré dans Neon."),{code:"PRICE_NOT_CONFIGURED"});const originalAmount=Number(price.rows[0].price_htg);let discountAmount=0;let promoId:string|null=null;if(promoCode){const promo=await client.query<{id:string;discount_percent:string|null;discount_amount:string|null;applicable_period:string|null;used_count:number;max_uses:number|null}>(`SELECT id,discount_percent,discount_amount,applicable_period,used_count,max_uses FROM promo_codes WHERE code=$1 AND is_active=true AND (expires_at IS NULL OR expires_at>NOW()) AND (max_uses IS NULL OR used_count<max_uses) FOR UPDATE`,[promoCode]);const p=promo.rows[0];if(p){if(p.applicable_period&&p.applicable_period!==periodMap[billingPeriod])throw Object.assign(new Error("Ce code promo ne correspond pas à la période sélectionnée."),{code:"PROMO_PERIOD_MISMATCH"});const redeemed=await client.query(`SELECT 1 FROM promo_redemptions WHERE promo_code_id=$1 AND user_id=$2 LIMIT 1`,[p.id,user.id]);if(redeemed.rowCount)throw Object.assign(new Error("Ce code promo a déjà été utilisé par ce compte."),{code:"PROMO_ALREADY_USED"});promoId=p.id;discountAmount=p.discount_percent!==null?Math.round(originalAmount*Number(p.discount_percent)/100*100)/100:Math.min(originalAmount,Number(p.discount_amount??0));}else{throw Object.assign(new Error("Code promo invalide ou expiré."),{code:"INVALID_PROMO"})}}
 const amount=Math.max(0,originalAmount-discountAmount);const payment=await client.query<{id:string}>(`INSERT INTO payments(user_id,provider,plan,billing_period,phone_number,original_amount,discount_amount,amount,currency,promo_code_id,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'HTG',$9,'pending') RETURNING id`,[user.id,provider,plan,periodMap[billingPeriod],phone,originalAmount,discountAmount,amount,promoId]);return{id:payment.rows[0].id,amountHTG:amount,discountAmount,promoApplied:Boolean(promoId)}});return res.status(201).json({transactionId:tx.id,amountHTG:tx.amountHTG,discountAmountHTG:tx.discountAmount,promoApplied:tx.promoApplied,checkoutUrl:undefined})}catch(error){console.error("[payments/create] error",error);const code=error&&typeof error==="object"&&"code" in error?String((error as any).code):"";if(code==="PROMO_ALREADY_USED"||code==="PROMO_PERIOD_MISMATCH")return res.status(409).json({error:(error as Error).message,code});if(code==="INVALID_PROMO")return res.status(400).json({error:(error as Error).message,code});if(code==="PRICE_NOT_CONFIGURED")return res.status(400).json({error:(error as Error).message,code});return res.status(503).json({error:"Création du paiement temporairement indisponible.",code:"PAYMENT_SERVICE_UNAVAILABLE"})}}
