import type { VercelRequest,VercelResponse } from "@vercel/node";
import { getUser } from "../_lib/auth";
import { query,transaction } from "../_lib/db";
const prices={flash:65.85,pro:250,gold:2500} as const;
function price(plan:"flash"|"pro"|"gold",period:"month"|"year"|"lifetime"){if(plan==="flash")return 65.85;if(period==="month")return prices[plan];if(period==="year")return Math.round(prices[plan]*12*0.87*100)/100;const env=process.env[`LIFETIME_${plan.toUpperCase()}_HTG`];return env?Number(env):null;}
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=="POST")return res.status(405).json({error:"Méthode non autorisée"});try{const user=await getUser(req);if(!user)return res.status(401).json({error:"Connexion requise."});const plan=String(req.body?.plan) as "flash"|"pro"|"gold";const billingPeriod=String(req.body?.billingPeriod) as "month"|"year"|"lifetime";const provider=String(req.body?.provider) as "zakapro"|"moncash"|"natcash";const phone=String(req.body?.phone??"").trim();const promoCode=String(req.body?.promoCode??"").trim().toUpperCase();if(!["flash","pro","gold"].includes(plan)||!["month","year","lifetime"].includes(billingPeriod)||!["zakapro","moncash","natcash"].includes(provider))return res.status(400).json({error:"Paramètres de paiement invalides."});if(!/^\+?509\d{8}$/.test(phone.replace(/[\s-]/g,"")))return res.status(400).json({error:"Numéro haïtien invalide."});const amount=price(plan,billingPeriod);if(amount===null)return res.status(400).json({error:"Le tarif À vie n'est pas encore configuré côté serveur."});let finalAmount=amount;let promoId:string|null=null;if(promoCode){const p=await query<{id:string;discount_percent:number;discount_amount_htg:number}>("SELECT id,discount_percent,COALESCE(discount_amount_htg,0) AS discount_amount_htg FROM promo_codes WHERE code=$1 AND active=true AND valid_from<=now() AND (valid_until IS NULL OR valid_until>=now()) AND (max_uses IS NULL OR used_count<max_uses)",[promoCode]);if(p.rows[0]){promoId=p.rows[0].id;finalAmount=Math.max(0,finalAmount*(1-Number(p.rows[0].discount_percent)/100)-Number(p.rows[0].discount_amount_htg));}}
 const tx=await transaction(async client=>{const r=await client.query<{id:string}>("INSERT INTO payments(user_id,provider,plan,billing_period,amount_htg,phone,promo_code,status,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,'pending',now()+interval '30 minutes') RETURNING id",[user.id,provider,plan,billingPeriod,finalAmount,phone,promoCode||null]);if(promoId)await client.query("INSERT INTO promo_redemptions(promo_code_id,user_id,payment_id) VALUES($1,$2,$3) ON CONFLICT(promo_code_id,user_id) DO NOTHING",[promoId,user.id,r.rows[0].id]);return r.rows[0].id;});
 let checkoutUrl:string|undefined;const zakaproUrl=process.env.ZAKAPRO_API_URL; if(zakaproUrl&&provider==="zakapro"){/* Adapter intentionally stays server-side; map fields to the real ZakaPro contract when credentials are provided. */}
 return res.status(201).json({transactionId:tx,amountHTG:finalAmount,checkoutUrl});}catch(e){console.error(e);return res.status(500).json({error:"Création du paiement impossible."});}}
