import type { VercelRequest, VercelResponse } from "@vercel/node";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import crypto from "node:crypto";
import nodemailer from "nodemailer";
import { Pool, type PoolClient, type QueryResultRow } from "pg";
import detectHandler from "../src/server/api/detect";
import humanizeHandler from "../src/server/api/humanize";
import settingsHandler from "../src/server/api/settings";
import copyleaksScanHandler from "../src/server/api/copyleaksScan";
import zakaproWebhookHandler from "../src/server/api/zakaproWebhook";

const COOKIE = "oligens_session";
const MAX_BYTES = 25 * 1024 * 1024;

type AuthUser = { id: string; email: string; email_verified: boolean };
type SubscriptionRow = { plan: "free" | "flash" | "pro" | "gold"; status: "active" | "expired" | "cancelled" | "pending"; billing_period: "monthly" | "yearly" | "lifetime" | null; expires_at: string | null; started_at: string };

let pool: Pool | undefined;
function dbUrl() { const value = process.env.DATABASE_URL?.trim(); if (!value) throw new Error("DATABASE_URL is not configured."); return value; }
function getPool() { if (pool) return pool; pool = new Pool({ connectionString: dbUrl(), max: 5, idleTimeoutMillis: 10_000, connectionTimeoutMillis: 10_000, ssl: { rejectUnauthorized: false }, application_name: "oligens-detector" }); pool.on("error", e => console.error("[database] idle client error", e)); return pool; }
async function query<T extends QueryResultRow = QueryResultRow>(text: string, values: unknown[] = []) { return getPool().query<T>(text, values); }
async function transaction<T>(fn: (client: PoolClient) => Promise<T>): Promise<T> { const client = await getPool().connect(); try { await client.query("BEGIN"); const result = await fn(client); await client.query("COMMIT"); return result; } catch (error) { try { await client.query("ROLLBACK"); } catch (e) { console.error("[database] rollback error", e); } throw error; } finally { client.release(); } }
function authSecret() { const value = process.env.AUTH_SECRET?.trim(); if (!value) throw new Error("AUTH_SECRET is not configured."); if (value.length < 32) throw new Error("AUTH_SECRET must contain at least 32 characters."); return value; }
function cookie(req: VercelRequest) { return (req.headers.cookie ?? "").split(";").map(v => v.trim()).find(v => v.startsWith(`${COOKIE}=`))?.slice(COOKIE.length + 1); }
async function getUser(req: VercelRequest): Promise<AuthUser | null> { const token = cookie(req); if (!token) return null; let payload: jwt.JwtPayload; try { payload = jwt.verify(token, authSecret(), { issuer: "oligens-detector" }) as jwt.JwtPayload; } catch { return null; } if (!payload.sub) return null; const result = await query<AuthUser>("SELECT id,email,email_verified FROM users WHERE id=$1", [payload.sub]); return result.rows[0] ?? null; }
function setSession(res: VercelResponse, userId: string) { const token = jwt.sign({ sub: userId }, authSecret(), { expiresIn: "30d", issuer: "oligens-detector" }); const secure = process.env.VERCEL_ENV === "production" ? "Secure; " : ""; res.setHeader("Set-Cookie", `${COOKIE}=${token}; Path=/; HttpOnly; SameSite=Lax; ${secure}Max-Age=2592000`); }
function clearSession(res: VercelResponse) { res.setHeader("Set-Cookie", `${COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0`); }
function hashCode(code: string) { return crypto.createHash("sha256").update(code).digest("hex"); }
function randomCode() { return String(crypto.randomInt(100000, 1000000)); }
function body(req: VercelRequest) { return (req.body ?? {}) as Record<string, unknown>; }
function asNumber(value: unknown, fallback = 0) { const n = Number(value); return Number.isFinite(n) ? n : fallback; }
function method(req: VercelRequest, res: VercelResponse, expected: string) { if (req.method !== expected) { res.status(405).json({ error: "Méthode non autorisée" }); return false; } return true; }

async function authMe(req: VercelRequest, res: VercelResponse) { if (!method(req, res, "GET")) return; try { if (!process.env.DATABASE_URL?.trim()) return res.status(503).json({ error: "Base de données non configurée.", code: "DATABASE_NOT_CONFIGURED" }); const user = await getUser(req); if (!user) return res.status(401).json({ user: null }); const result = await query<SubscriptionRow>(`SELECT CASE WHEN plan <> 'free' AND status = 'active' AND expires_at IS NOT NULL AND expires_at <= NOW() THEN 'free'::subscription_plan ELSE plan END AS plan, CASE WHEN plan <> 'free' AND status = 'active' AND expires_at IS NOT NULL AND expires_at <= NOW() THEN 'active'::subscription_status ELSE status END AS status, CASE WHEN plan <> 'free' AND status = 'active' AND expires_at IS NOT NULL AND expires_at <= NOW() THEN 'monthly'::billing_period ELSE billing_period END AS billing_period, CASE WHEN plan <> 'free' AND status = 'active' AND expires_at IS NOT NULL AND expires_at <= NOW() THEN NULL ELSE expires_at END AS expires_at, started_at FROM subscriptions WHERE user_id = $1 LIMIT 1`, [user.id]); const sub = result.rows[0] ?? { plan: "free" as const, status: "active" as const, billing_period: "monthly" as const, expires_at: null, started_at: new Date().toISOString() }; let flashAnalysesToday = 0; if (sub.plan === "flash") { const usage = await query<{ count: string }>(`SELECT COUNT(*)::text AS count FROM usage_events WHERE user_id = $1 AND event_type = 'analysis' AND created_at >= DATE_TRUNC('day', NOW())`, [user.id]); flashAnalysesToday = Number(usage.rows[0]?.count ?? 0); } return res.status(200).json({ user, subscription: { plan: sub.plan, status: sub.status, period: sub.billing_period, currentPeriodEnd: sub.expires_at, flashStartedAt: sub.plan === "flash" ? sub.started_at : null, flashAnalysesToday } }); } catch (error) { console.error("[auth/me] error", error); const message = error instanceof Error ? error.message : "Service indisponible."; if (message.includes("AUTH_SECRET")) return res.status(503).json({ error: "Authentification non configurée sur le serveur.", code: "AUTH_SECRET_NOT_CONFIGURED" }); if (message.includes("DATABASE_URL") || /ENOTFOUND|ECONNREFUSED|ETIMEDOUT|certificate|SSL|connection/i.test(message)) return res.status(503).json({ error: "Base de données temporairement indisponible.", code: "DATABASE_UNAVAILABLE" }); return res.status(500).json({ error: "Erreur interne pendant la récupération de la session.", code: "AUTH_ME_INTERNAL_ERROR" }); } }
async function authSignin(req: VercelRequest, res: VercelResponse) { if (!method(req, res, "POST")) return; try { if (!process.env.DATABASE_URL?.trim()) return res.status(503).json({ error: "Base de données non configurée.", code: "DATABASE_NOT_CONFIGURED" }); if (!process.env.AUTH_SECRET?.trim()) return res.status(503).json({ error: "Authentification non configurée.", code: "AUTH_SECRET_NOT_CONFIGURED" }); const email = String(body(req).email ?? "").trim().toLowerCase(), password = String(body(req).password ?? ""); if (!/^\S+@\S+\.\S+$/.test(email) || !password) return res.status(400).json({ error: "E-mail ou mot de passe invalide." }); const result = await query<{ id: string; password_hash: string; email_verified: boolean }>("SELECT id,password_hash,email_verified FROM users WHERE email=$1", [email]); const user = result.rows[0]; if (!user || !(await bcrypt.compare(password, user.password_hash))) return res.status(401).json({ error: "E-mail ou mot de passe incorrect." }); if (!user.email_verified) return res.status(403).json({ error: "Vérifiez votre e-mail avant de vous connecter.", code: "EMAIL_NOT_VERIFIED" }); setSession(res, user.id); return res.status(200).json({ user: { id: user.id, email } }); } catch (error) { console.error("[auth/signin] error", error); const message = error instanceof Error ? error.message : "Connexion impossible."; if (message.includes("AUTH_SECRET")) return res.status(503).json({ error: "Authentification non configurée sur le serveur.", code: "AUTH_SECRET_NOT_CONFIGURED" }); return res.status(503).json({ error: "Base de données ou service d'authentification indisponible.", code: "AUTH_DATABASE_UNAVAILABLE" }); } }
function authSignout(req: VercelRequest, res: VercelResponse) { if (!method(req, res, "POST")) return; clearSession(res); return res.status(200).json({ ok: true }); }
function mailer() { const user = process.env.GMAIL_SMTP_USER?.trim(), pass = process.env.GMAIL_SMTP_APP_PASSWORD?.replace(/\s+/g, ""); if (!user || !pass) throw new Error("Gmail SMTP n'est pas configuré sur le serveur."); return nodemailer.createTransport({ host: "smtp.gmail.com", port: 465, secure: true, auth: { user, pass } }); }
async function authSignup(req: VercelRequest, res: VercelResponse) { if (!method(req, res, "POST")) return; try { if (!process.env.DATABASE_URL?.trim()) return res.status(503).json({ error: "Base de données non configurée.", code: "DATABASE_NOT_CONFIGURED" }); const b = body(req), email = String(b.email ?? "").trim().toLowerCase(), password = String(b.password ?? ""), firstName = String(b.firstName ?? b.first_name ?? "").trim() || null, lastName = String(b.lastName ?? b.last_name ?? "").trim() || null; if (!/^\S+@\S+\.\S+$/.test(email)) return res.status(400).json({ error: "E-mail invalide.", code: "INVALID_EMAIL" }); if (password.length < 8) return res.status(400).json({ error: "Le mot de passe doit contenir au moins 8 caractères.", code: "WEAK_PASSWORD" }); const existing = await query<{ id: string }>("SELECT id FROM users WHERE lower(email)=lower($1) LIMIT 1", [email]); if (existing.rowCount) return res.status(409).json({ error: "Un compte existe déjà avec cet e-mail.", code: "EMAIL_EXISTS" }); const code = randomCode(), passwordHash = await bcrypt.hash(password, 12), codeHash = hashCode(code), userId = crypto.randomUUID(); await transaction(async client => { const exists = await client.query("SELECT id FROM users WHERE lower(email)=lower($1) LIMIT 1 FOR UPDATE", [email]); if (exists.rowCount) throw Object.assign(new Error("Un compte existe déjà avec cet e-mail."), { code: "EMAIL_EXISTS" }); await client.query(`INSERT INTO users (id,email,password_hash,first_name,last_name,email_verified,verification_code_hash,verification_code_expires_at,verification_attempts) VALUES ($1,$2,$3,$4,$5,FALSE,$6,NOW()+INTERVAL '15 minutes',0)`, [userId,email,passwordHash,firstName,lastName,codeHash]); }); try { const transport = mailer(); await transport.verify(); await transport.sendMail({ from: process.env.GMAIL_SMTP_USER, to: email, subject: "Votre code de vérification Oligens Detector", text: `Votre code Oligens Detector est ${code}. Il expire dans 15 minutes.`, html: `<h2>Oligens Detector</h2><p>Votre code de vérification :</p><p style="font-size:32px;font-weight:700;letter-spacing:8px">${code}</p><p>Ce code expire dans 15 minutes.</p>` }); } catch (mailError) { console.error("[auth/signup] SMTP error", mailError); return res.status(503).json({ error: "Compte créé mais l'e-mail de vérification n'a pas pu être envoyé.", code: "EMAIL_SERVICE_UNAVAILABLE", canRetryVerification: true }); } return res.status(201).json({ needsVerification: true, userId }); } catch (error) { console.error("[auth/signup] error", error); const code = error instanceof Error ? (error as Error & { code?: string }).code : undefined; if (code === "23505" || code === "EMAIL_EXISTS") return res.status(409).json({ error: "Un compte existe déjà avec cet e-mail.", code: "EMAIL_EXISTS" }); return res.status(500).json({ error: "Erreur interne pendant l'inscription.", code: "SIGNUP_INTERNAL_ERROR" }); } }
async function authVerify(req: VercelRequest, res: VercelResponse) { if (!method(req, res, "POST")) return; try { const b = body(req), email = String(b.email ?? "").trim().toLowerCase(), code = String(b.code ?? "").trim(); if (!email || !/^\d{6}$/.test(code)) return res.status(400).json({ error: "E-mail ou code invalide." }); const r = await query<{ id: string; verification_code_hash: string | null; verification_expires_at: string | null }>("SELECT id,verification_code_hash,verification_code_expires_at AS verification_expires_at FROM users WHERE email=$1", [email]); const u = r.rows[0]; if (!u) return res.status(404).json({ error: "Compte introuvable." }); if (!u.verification_code_hash || !u.verification_expires_at || new Date(u.verification_expires_at) <= new Date()) return res.status(400).json({ error: "Code expiré. Demandez un nouveau code." }); if (hashCode(code) !== u.verification_code_hash) return res.status(400).json({ error: "Code incorrect." }); await query("UPDATE users SET email_verified=true,verification_code_hash=NULL,verification_code_expires_at=NULL,verification_attempts=0 WHERE id=$1", [u.id]); setSession(res, u.id); return res.status(200).json({ verified: true }); } catch (error) { console.error("[auth/verify] error", error); return res.status(503).json({ error: "Vérification temporairement indisponible." }); } }

async function analyses(req: VercelRequest, res: VercelResponse) { try { const user = await getUser(req); if (!user) return res.status(401).json({ error: "Authentification requise." }); if (req.method === "GET") { const limit = Math.min(100, Math.max(1, Number(req.query.limit ?? 50))); const result = await query(`SELECT id,file_name,file_type,file_size_kb,word_count,ai_score,plagiarism_score,reference_score,human_score,language,analysis_result,processing_time_ms,created_at FROM analyses WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2`, [user.id, limit]); return res.status(200).json({ analyses: result.rows }); } return res.status(405).json({ error: "Méthode non autorisée" }); } catch (error) { console.error("[analyses] error", error); return res.status(503).json({ error: "Données d'analyse temporairement indisponibles.", code: "ANALYSES_UNAVAILABLE" }); } }
async function analysisCreate(req: VercelRequest, res: VercelResponse) { if (!method(req, res, "POST")) return; try { const user = await getUser(req); if (!user) return res.status(401).json({ error: "Authentification requise." }); const b = body(req), fileName = String(b.fileName ?? "").trim(), result = (b.result ?? {}) as Record<string, unknown>; if (!fileName) return res.status(400).json({ error: "Nom de fichier requis." }); const lower = fileName.toLowerCase(), fileType = lower.endsWith(".pdf") ? "pdf" : lower.endsWith(".docx") || lower.endsWith(".doc") ? "docx" : "txt", engine = (result.engine ?? {}) as Record<string, unknown>, wordCount = Math.max(0, Math.round(asNumber(engine.words))), characterCount = Math.max(0, Math.round(asNumber(engine.characters))), sentenceCount = Math.max(0, Math.round(asNumber(engine.sentences))), processingTimeMs = Math.max(0, Math.round(asNumber(engine.durationMs))), scores = (result.scores ?? {}) as Record<string, unknown>, aiScore = asNumber(scores.ai), plagiarismScore = asNumber(scores.plagiarism), referenceScore = asNumber(scores.reference), humanScore = asNumber(scores.human), language = typeof result.language === "string" ? result.language : null; const id = crypto.randomUUID(); await query(`INSERT INTO analyses(id,user_id,file_name,file_type,file_size_kb,word_count,character_count,sentence_count,ai_score,plagiarism_score,reference_score,human_score,language,analysis_result,processing_time_ms) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`, [id,user.id,fileName,fileType,asNumber(b.fileSizeKb),wordCount,characterCount,sentenceCount,aiScore,plagiarismScore,referenceScore,humanScore,language,JSON.stringify(result),processingTimeMs]); return res.status(201).json({ id }); } catch (error) { console.error("[analyses/create] error", error); return res.status(503).json({ error: "Enregistrement de l'analyse temporairement indisponible.", code: "ANALYSIS_CREATE_UNAVAILABLE" }); } }
async function institutionalDatabases(req: VercelRequest, res: VercelResponse) { try { const user = await getUser(req); if (!user) return res.status(401).json({ error: "Authentification requise." }); if (req.method === "GET") { const result = await query(`SELECT id,name,description,document_count,metadata,created_at,updated_at FROM institutional_databases WHERE user_id=$1 ORDER BY updated_at DESC`, [user.id]); return res.status(200).json({ databases: result.rows }); } if (req.method === "POST") { const b = body(req), name = String(b.name ?? "").trim(); if (!name) return res.status(400).json({ error: "Nom requis." }); const id = crypto.randomUUID(); await query(`INSERT INTO institutional_databases(id,user_id,name,description,document_count,metadata) VALUES($1,$2,$3,$4,$5,$6)`, [id,user.id,name,typeof b.description === "string" ? b.description : null,Math.max(0,Math.round(asNumber(b.documentCount))),JSON.stringify(b.metadata ?? {})]); return res.status(201).json({ id }); } return res.status(405).json({ error: "Méthode non autorisée" }); } catch (error) { console.error("[institutional-databases] error", error); return res.status(503).json({ error: "Bases institutionnelles temporairement indisponibles.", code: "INSTITUTIONAL_DATABASES_UNAVAILABLE" }); } }
async function reports(req: VercelRequest, res: VercelResponse) { try { const user = await getUser(req); if (!user) return res.status(401).json({ error: "Authentification requise." }); if (req.method === "GET") { const result = await query(`SELECT id,analysis_id,report_type,file_url,report_data,created_at FROM reports WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100`, [user.id]); return res.status(200).json({ reports: result.rows }); } return res.status(405).json({ error: "Méthode non autorisée" }); } catch (error) { console.error("[reports] error", error); return res.status(503).json({ error: "Rapports temporairement indisponibles.", code: "REPORTS_UNAVAILABLE" }); } }
async function stats(req: VercelRequest, res: VercelResponse) { try { const user = await getUser(req); if (!user) return res.status(401).json({ error: "Authentification requise." }); if (req.method === "GET") { const [total, average, ai, plagiarism, usage] = await Promise.all([query<{ count: string }>("SELECT COUNT(*)::text AS count FROM analyses WHERE user_id=$1", [user.id]),query<{ value: string }>("SELECT COALESCE(AVG(ai_score),0)::text AS value FROM analyses WHERE user_id=$1", [user.id]),query<{ value: string }>("SELECT COALESCE(AVG(human_score),0)::text AS value FROM analyses WHERE user_id=$1", [user.id]),query<{ value: string }>("SELECT COALESCE(AVG(plagiarism_score),0)::text AS value FROM analyses WHERE user_id=$1", [user.id]),query<{ count: string }>("SELECT COUNT(*)::text AS count FROM usage_events WHERE user_id=$1", [user.id])]); return res.status(200).json({ totalAnalyses: Number(total.rows[0]?.count ?? 0), averageAiScore: Number(average.rows[0]?.value ?? 0), averageHumanScore: Number(ai.rows[0]?.value ?? 0), averagePlagiarismScore: Number(plagiarism.rows[0]?.value ?? 0), usageEvents: Number(usage.rows[0]?.count ?? 0) }); } return res.status(405).json({ error: "Méthode non autorisée" }); } catch (error) { console.error("[stats] error", error); return res.status(503).json({ error: "Statistiques temporairement indisponibles.", code: "STATS_UNAVAILABLE" }); } }

export default async function handler(req: VercelRequest, res: VercelResponse) { const raw = req.query.all; const parts = Array.isArray(raw) ? raw : typeof raw === "string" ? raw.split("/") : []; const path = parts.filter(Boolean).join("/"); switch (path) { case "detect": return detectHandler(req,res); case "humanize": return humanizeHandler(req,res); case "settings": return settingsHandler(req,res); case "copyleaks/scan": return copyleaksScanHandler(req,res); case "webhooks/zakapro": return zakaproWebhookHandler(req,res); case "auth/me": return authMe(req,res); case "auth/signin": return authSignin(req,res); case "auth/signout": return authSignout(req,res); case "auth/signup": return authSignup(req,res); case "auth/verify": return authVerify(req,res); case "analyses": return analyses(req,res); case "analyses/create": return analysisCreate(req,res); case "institutional-databases": return institutionalDatabases(req,res); case "reports": return reports(req,res); case "stats": return stats(req,res); default: return res.status(404).json({ error: "API route not found", path }); } }
